### ISSUE TITLE
回線が細い状態だとタイムアウトで落ちる

### ISSUE THREAD

**Issue by meronmks** [meronmks/Chairs#49]
流石にタイムアウトで落ちるのは駄目でしょ

**Comment by meronmks** [comment]
com.sys1yagi.mastodon4j.api.exception.Mastodon4jRequestException: java.net.SocketTimeoutException: timeout
	at com.sys1yagi.mastodon4j.MastodonClient.get(MastodonClient.kt:92)
	at com.sys1yagi.mastodon4j.api.method.Notifications$getNotifications$1.invoke(Notifications.kt:23)
	at com.sys1yagi.mastodon4j.api.method.Notifications$getNotifications$1.invoke(Notifications.kt:17)
	at com.sys1yagi.mastodon4j.MastodonRequest.execute(MastodonRequest.kt:37)
	at com.meronmks.chairs.Tools.MastodonNotificationTool$getNotificationAsync$1.doResume(MastodonNotificationTool.kt:23)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlinx.coroutines.experimental.DispatchTask.run(CoroutineDispatcher.kt:120)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1383)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:256)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1123)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1961)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1909)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:128)

**Comment by meronmks** [comment]
あれ以来発生しない、もう2週ほど様子見して同じ原因で落ちなければ閉じる

**Comment by meronmks** [comment]
04b9ffbc6361596de7586adf36603bccd9452d9e でたぶん修正
