### ISSUE TITLE
ライブラリが内部で使用してるokhttp3でクラッシュする

### ISSUE THREAD

**Issue by meronmks** [meronmks/Chairs#50]
java.lang.Error: okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1168)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

**Comment by meronmks** [comment]
アプリを落としていてもクラッシュしてることがあるのでストリーミングからちゃんと切り離せてない？
