### ISSUE TITLE
リストが空の状態の更新でクラッシュする

### ISSUE THREAD

**Issue by meronmks** [meronmks/Chairs#67]
放っておくとDeployGate側のログが消えるのでメモ

java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
	at java.util.ArrayList.get(ArrayList.java:413)
	at android.widget.ArrayAdapter.getItem(ArrayAdapter.java:349)
	at com.meronmks.chairs.ViewPages.Fragments.ListTLFragment$onActivityCreated$1.onRefresh(ListTLFragment.kt:53)

**Comment by meronmks** [comment]
ac5cb6fd993b5bcd29e04a2a3aa7c650ed057bf7 で直した
